### ISSUE TITLE
This provider have to use terraform-provider-sdk v2

### ISSUE THREAD

**Issue by cappyzawa** [AthenZ/terraform-provider-athenz#16]
[Announcing HashiCorp Terraform 1\.0 General Availability](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability)

> The Terraform Plugin SDK is a framework that lets developers create and maintain Terraform providers. HashiCorp will be ending support for the version 1 release of the Plugin SDK on July 31, 2021. Users of the Terraform CLI and Terraform Cloud are not affected by this and do not need to take any action. Maintainers of Terraform providers who are impacted are encouraged to use our upgrade guide to move to version 2 of the Terraform Plugin SDK. Follow our tutorials to develop your first provider. Additional information can be found in the Terraform Provider Developer Community Discuss forum: End of Life Timeline for v1 of the Terraform Plugin SDK.

This provider doesn't use SDK v2. (https://github.com/AthenZ/terraform-provider-athenz/blob/main/go.mod#L9)

**Comment by dvirguttman** [comment]
Thanks for reporting that issue.
Will address it asap

**Comment by dvirguttman** [comment]
athenz terraform provider v1.0.3 upgraded successfully terraform sdk to v2
