### ISSUE TITLE
example doesn't show how to "get" the provider

### ISSUE THREAD

**Issue by scr-oath** [AthenZ/terraform-provider-athenz#33]
The example listed on https://registry.terraform.io/providers/AthenZ/athenz/latest/docs does not explain how to "get" the provider.

Adding a stanza like this would be super helpful

```
terraform {
  required_version = ">= 1.1"
  required_providers {
    athenz = {
      source = "AthenZ/athenz"
      version = ">= 1.0.5"
    }
  }
}
```

**Comment by abvaidya** [comment]
"Use Provider" button on top right hand side on the provider page should show this.

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/31417623/186979868-1c6c4b55-5e6a-4379-9e52-7c3fbd25c689.png">

**Comment by abvaidya** [comment]
Example usage section in Terraform provider doc is updated with provider definition block. https://github.com/AthenZ/terraform-provider-athenz/pull/34
